{
# Attention, partially generated by AI
  description = "C3 dev environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        version = "0.7.0";

        archiveUrl = "https://github.com/c3lang/c3c/releases/download/v${version}/c3-linux.tar.gz";

        extractedArchive = pkgs.stdenv.mkDerivation {
          pname = "c3c";
          inherit version;

          src = builtins.fetchTarball {
            url = archiveUrl;
            sha256 = "09kjxrphmpnprk2v8mg7zzczli6crhlqm6xmzw2632zj8awqi9vj";
          };

          installPhase = ''
            mkdir -p $out
            cp -r * $out/
          '';
        };

        libraries = with pkgs; [
          libxml2.out
          zlib
          ncurses
          zstd.out
          stdenv.cc.cc.lib

        ];

        getLibDirs = pkg: "${pkg}/lib";
      in
        {
        devShells.default = pkgs.mkShell {
          buildInputs = libraries;
          shellHook = ''
            EXTRACTED_DIR=${extractedArchive}
            export PATH=$EXTRACTED_DIR:$PATH
            export LD_LIBRARY_PATH=${pkgs.lib.concatStringsSep ":" (map getLibDirs libraries)}:$LD_LIBRARY_PATH
            echo "Environment established"
          '';
        };
      }
    );
}
